### ISSUE TITLE
the app from {https://apps.smarthealthit.org/app/ascvd-risk-calculator} didnt work

### ISSUE THREAD

**Issue by zorz1986** [cerner/ascvd-risk-calculator#9]
the app doesnt response when i open with the latest version of firefox and google chrome.
it is working for me only on safe mode with firefox or with older versions

**Comment by shriniketsarkar** [comment]
@zorz1986  Can you describe the issue that you are facing ?

**Comment by kpshek** [comment]
@zorz1986 - To expand a bit on what @shriniketsarkar is asking, can you be more specific as to the issue you are seeing?

For instance, if you look in the Developer Console/Tools on each of those browsers, are there any Javascript warnings/errors?

If your issue title, you mentioned the URL https://apps.smarthealthit.org/app/ascvd-risk-calculator. Are you launching the app by clicking the "Try App" button there?

**Comment by zorz1986** [comment]
i find out what was wrong, the app didnt work if i havent run the broser on english versionthanks for the response 

    Στις 7:13 μ.μ. Τετάρτη, 6 Δεκεμβρίου 2017, ο/η Kevin Shekleton <notifications@github.com> έγραψε:
 

 @zorz1986 - To expand a bit on what @shriniketsarkar is asking, can you be more specific as to the issue you are seeing?For instance, if you look in the Developer Console/Tools on each of those browsers, are there any Javascript warnings/errors?If your issue title, you mentioned the URL https://apps.smarthealthit.org/app/ascvd-risk-calculator. Are you launching the app by clicking the "Try App" button there?—
